services:
  db:
    image: postgres:15.5-bullseye
    container_name: aula07-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aula07-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - aula07-network

networks:
  aula07-network:
    driver: bridge